export * from './s-d-e-agent.service';
import { SDEAgentService } from './s-d-e-agent.service';
export * from './s-d-e-certificates.service';
import { SDECertificatesService } from './s-d-e-certificates.service';
export * from './s-d-e-character.service';
import { SDECharacterService } from './s-d-e-character.service';
export * from './s-d-e-corporation.service';
import { SDECorporationService } from './s-d-e-corporation.service';
export * from './s-d-e-dogma.service';
import { SDEDogmaService } from './s-d-e-dogma.service';
export * from './s-d-e-e-v-e.service';
import { SDEEVEService } from './s-d-e-e-v-e.service';
export * from './s-d-e-industry.service';
import { SDEIndustryService } from './s-d-e-industry.service';
export * from './s-d-e-inventory.service';
import { SDEInventoryService } from './s-d-e-inventory.service';
export * from './s-d-e-map.service';
import { SDEMapService } from './s-d-e-map.service';
export * from './s-d-e-planet.service';
import { SDEPlanetService } from './s-d-e-planet.service';
export * from './s-d-e-r-a-m.service';
import { SDERAMService } from './s-d-e-r-a-m.service';
export * from './s-d-e-skin.service';
import { SDESkinService } from './s-d-e-skin.service';
export * from './s-d-e-station.service';
import { SDEStationService } from './s-d-e-station.service';
export * from './s-d-e-translation.service';
import { SDETranslationService } from './s-d-e-translation.service';
export * from './s-d-e-war.service';
import { SDEWarService } from './s-d-e-war.service';
export const APIS = [SDEAgentService, SDECertificatesService, SDECharacterService, SDECorporationService, SDEDogmaService, SDEEVEService, SDEIndustryService, SDEInventoryService, SDEMapService, SDEPlanetService, SDERAMService, SDESkinService, SDEStationService, SDETranslationService, SDEWarService];
