export * from './agent.service';
import { AgentService } from './agent.service';
export * from './certificates.service';
import { CertificatesService } from './certificates.service';
export * from './character.service';
import { CharacterService } from './character.service';
export * from './corporation.service';
import { CorporationService } from './corporation.service';
export * from './dogma.service';
import { DogmaService } from './dogma.service';
export * from './eVE.service';
import { EVEService } from './eVE.service';
export * from './industry.service';
import { IndustryService } from './industry.service';
export * from './inventory.service';
import { InventoryService } from './inventory.service';
export * from './map.service';
import { MapService } from './map.service';
export * from './planet.service';
import { PlanetService } from './planet.service';
export * from './rAM.service';
import { RAMService } from './rAM.service';
export * from './skin.service';
import { SkinService } from './skin.service';
export * from './station.service';
import { StationService } from './station.service';
export * from './translation.service';
import { TranslationService } from './translation.service';
export * from './war.service';
import { WarService } from './war.service';
export const APIS = [AgentService, CertificatesService, CharacterService, CorporationService, DogmaService, EVEService, IndustryService, InventoryService, MapService, PlanetService, RAMService, SkinService, StationService, TranslationService, WarService];
