/**
 * EveKit Frontend Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EveKitUserAccount } from './eveKitUserAccount';


/**
 * Authentication source for a user
 */
export interface EveKitUserAuthSource {
    owner?: EveKitUserAccount;
    userAccount?: EveKitUserAccount;
    body?: string;
    lastSignOn?: Date;
    /**
     * Unique source ID
     */
    sid?: number;
    account?: EveKitUserAccount;
    /**
     * Name of authentication source
     */
    source?: string;
    /**
     * Screen name for this source
     */
    screenName?: string;
    /**
     * Source specific authentication details
     */
    details?: string;
    /**
     * Last time (milliseconds UTC) this source was used to authenticate
     */
    last?: number;
}
