/**
 * EveKit Frontend Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EveKitUserAccount } from './eveKitUserAccount';


/**
 * User notification
 */
export interface EveKitUserNotification {
    /**
     * Unique notification ID
     */
    nid?: number;
    account?: EveKitUserAccount;
    /**
     * Note creation time
     */
    time?: number;
    /**
     * Note content
     */
    content?: string;
    /**
     * Note read time
     */
    read?: number;
    /**
     * Note deleted
     */
    trash?: boolean;
}
