/**
 * EveKit Frontend Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SyncEndpointStats {
    endpoint?: SyncEndpointStats.EndpointEnum;
    attempts?: number;
    failures?: number;
}
export namespace SyncEndpointStats {
    export type EndpointEnum = 'CHAR_ASSETS' | 'CORP_ASSETS' | 'CHAR_BOOKMARKS' | 'CORP_BOOKMARKS' | 'CHAR_CALENDAR' | 'CHAR_MEDALS' | 'CHAR_STANDINGS' | 'CHAR_AGENTS' | 'CHAR_BLUEPRINTS' | 'CHAR_FATIGUE' | 'CHAR_NOTIFICATIONS' | 'CHAR_CORP_ROLES' | 'CHAR_TITLES' | 'CHAR_CLONES' | 'CHAR_IMPLANTS' | 'CHAR_CONTACTS' | 'CORP_CONTACTS' | 'CHAR_ALLIANCE_CONTACTS' | 'CHAR_CONTRACTS' | 'CORP_CONTRACTS' | 'CORP_BLUEPRINTS' | 'CORP_CONTAINER_LOGS' | 'CORP_MEMBERSHIP' | 'CORP_DIVISIONS' | 'CORP_FACILITIES' | 'CORP_MEDALS' | 'CORP_STANDINGS' | 'CORP_STARBASES' | 'CORP_STRUCTURES' | 'CORP_TITLES' | 'CORP_TRACK_MEMBERS' | 'CORP_WALLET_BALANCE' | 'CORP_WALLET_JOURNAL' | 'CORP_WALLET_TRANSACTIONS' | 'CORP_FACTION_WAR' | 'CHAR_FACTION_WAR' | 'CHAR_FITTINGS' | 'CHAR_FLEETS' | 'CHAR_INDUSTRY' | 'CHAR_MINING' | 'CORP_INDUSTRY' | 'CORP_MINING' | 'CHAR_KILL_MAIL' | 'CORP_KILL_MAIL' | 'CHAR_LOCATION' | 'CHAR_SHIP_TYPE' | 'CHAR_ONLINE' | 'CHAR_LOYALTY' | 'CHAR_MAIL' | 'CHAR_MARKET' | 'CORP_MARKET' | 'CHAR_OPPORTUNITIES' | 'CHAR_PLANETS' | 'CORP_CUSTOMS' | 'CHAR_SKILL_QUEUE' | 'CHAR_SKILLS' | 'CHAR_WALLET_BALANCE' | 'CHAR_WALLET_JOURNAL' | 'CHAR_WALLET_TRANSACTIONS' | 'CHAR_SHEET' | 'CORP_SHEET' | 'CORP_SHAREHOLDERS';
    export const EndpointEnum = {
        CHARASSETS: 'CHAR_ASSETS' as EndpointEnum,
        CORPASSETS: 'CORP_ASSETS' as EndpointEnum,
        CHARBOOKMARKS: 'CHAR_BOOKMARKS' as EndpointEnum,
        CORPBOOKMARKS: 'CORP_BOOKMARKS' as EndpointEnum,
        CHARCALENDAR: 'CHAR_CALENDAR' as EndpointEnum,
        CHARMEDALS: 'CHAR_MEDALS' as EndpointEnum,
        CHARSTANDINGS: 'CHAR_STANDINGS' as EndpointEnum,
        CHARAGENTS: 'CHAR_AGENTS' as EndpointEnum,
        CHARBLUEPRINTS: 'CHAR_BLUEPRINTS' as EndpointEnum,
        CHARFATIGUE: 'CHAR_FATIGUE' as EndpointEnum,
        CHARNOTIFICATIONS: 'CHAR_NOTIFICATIONS' as EndpointEnum,
        CHARCORPROLES: 'CHAR_CORP_ROLES' as EndpointEnum,
        CHARTITLES: 'CHAR_TITLES' as EndpointEnum,
        CHARCLONES: 'CHAR_CLONES' as EndpointEnum,
        CHARIMPLANTS: 'CHAR_IMPLANTS' as EndpointEnum,
        CHARCONTACTS: 'CHAR_CONTACTS' as EndpointEnum,
        CORPCONTACTS: 'CORP_CONTACTS' as EndpointEnum,
        CHARALLIANCECONTACTS: 'CHAR_ALLIANCE_CONTACTS' as EndpointEnum,
        CHARCONTRACTS: 'CHAR_CONTRACTS' as EndpointEnum,
        CORPCONTRACTS: 'CORP_CONTRACTS' as EndpointEnum,
        CORPBLUEPRINTS: 'CORP_BLUEPRINTS' as EndpointEnum,
        CORPCONTAINERLOGS: 'CORP_CONTAINER_LOGS' as EndpointEnum,
        CORPMEMBERSHIP: 'CORP_MEMBERSHIP' as EndpointEnum,
        CORPDIVISIONS: 'CORP_DIVISIONS' as EndpointEnum,
        CORPFACILITIES: 'CORP_FACILITIES' as EndpointEnum,
        CORPMEDALS: 'CORP_MEDALS' as EndpointEnum,
        CORPSTANDINGS: 'CORP_STANDINGS' as EndpointEnum,
        CORPSTARBASES: 'CORP_STARBASES' as EndpointEnum,
        CORPSTRUCTURES: 'CORP_STRUCTURES' as EndpointEnum,
        CORPTITLES: 'CORP_TITLES' as EndpointEnum,
        CORPTRACKMEMBERS: 'CORP_TRACK_MEMBERS' as EndpointEnum,
        CORPWALLETBALANCE: 'CORP_WALLET_BALANCE' as EndpointEnum,
        CORPWALLETJOURNAL: 'CORP_WALLET_JOURNAL' as EndpointEnum,
        CORPWALLETTRANSACTIONS: 'CORP_WALLET_TRANSACTIONS' as EndpointEnum,
        CORPFACTIONWAR: 'CORP_FACTION_WAR' as EndpointEnum,
        CHARFACTIONWAR: 'CHAR_FACTION_WAR' as EndpointEnum,
        CHARFITTINGS: 'CHAR_FITTINGS' as EndpointEnum,
        CHARFLEETS: 'CHAR_FLEETS' as EndpointEnum,
        CHARINDUSTRY: 'CHAR_INDUSTRY' as EndpointEnum,
        CHARMINING: 'CHAR_MINING' as EndpointEnum,
        CORPINDUSTRY: 'CORP_INDUSTRY' as EndpointEnum,
        CORPMINING: 'CORP_MINING' as EndpointEnum,
        CHARKILLMAIL: 'CHAR_KILL_MAIL' as EndpointEnum,
        CORPKILLMAIL: 'CORP_KILL_MAIL' as EndpointEnum,
        CHARLOCATION: 'CHAR_LOCATION' as EndpointEnum,
        CHARSHIPTYPE: 'CHAR_SHIP_TYPE' as EndpointEnum,
        CHARONLINE: 'CHAR_ONLINE' as EndpointEnum,
        CHARLOYALTY: 'CHAR_LOYALTY' as EndpointEnum,
        CHARMAIL: 'CHAR_MAIL' as EndpointEnum,
        CHARMARKET: 'CHAR_MARKET' as EndpointEnum,
        CORPMARKET: 'CORP_MARKET' as EndpointEnum,
        CHAROPPORTUNITIES: 'CHAR_OPPORTUNITIES' as EndpointEnum,
        CHARPLANETS: 'CHAR_PLANETS' as EndpointEnum,
        CORPCUSTOMS: 'CORP_CUSTOMS' as EndpointEnum,
        CHARSKILLQUEUE: 'CHAR_SKILL_QUEUE' as EndpointEnum,
        CHARSKILLS: 'CHAR_SKILLS' as EndpointEnum,
        CHARWALLETBALANCE: 'CHAR_WALLET_BALANCE' as EndpointEnum,
        CHARWALLETJOURNAL: 'CHAR_WALLET_JOURNAL' as EndpointEnum,
        CHARWALLETTRANSACTIONS: 'CHAR_WALLET_TRANSACTIONS' as EndpointEnum,
        CHARSHEET: 'CHAR_SHEET' as EndpointEnum,
        CORPSHEET: 'CORP_SHEET' as EndpointEnum,
        CORPSHAREHOLDERS: 'CORP_SHAREHOLDERS' as EndpointEnum
    }
}
