/**
 * EveKit Frontend Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ServiceError } from '../model/serviceError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CredentialService {

    protected basePath = 'http://localhost:8888/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Remove the ESI credential from a sync account
     * 
     * @param aid ID of sync account owning credential to be deleted.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clearESICredential(aid: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public clearESICredential(aid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public clearESICredential(aid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public clearESICredential(aid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (aid === null || aid === undefined) {
            throw new Error('Required parameter aid was null or undefined when calling clearESICredential.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/ws/v1/cred/cred_esi/${encodeURIComponent(String(aid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Handle OAuth callback for ESI credential setting
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public esiCredentialCallback(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public esiCredentialCallback(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public esiCredentialCallback(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public esiCredentialCallback(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<any>(`${this.basePath}/ws/v1/cred/esi_callback`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Set the ESI credential for a synchronized account by starting an OAuth flow.
     * 
     * @param aid ID of sync account owning credential to be created.
     * @param scopes Space separated list of scopes for credential
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setESICredential(aid: number, scopes: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public setESICredential(aid: number, scopes: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public setESICredential(aid: number, scopes: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public setESICredential(aid: number, scopes: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (aid === null || aid === undefined) {
            throw new Error('Required parameter aid was null or undefined when calling setESICredential.');
        }
        if (scopes === null || scopes === undefined) {
            throw new Error('Required parameter scopes was null or undefined when calling setESICredential.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/ws/v1/cred/cred_esi/${encodeURIComponent(String(aid))}`,
            scopes,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
