/**
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * EveKit Access Key info
 */
export interface KeyInfo { 
    /**
     * key type, either 'corporation' or 'character'
     */
    keyType?: string;
    /**
     * key entity name, either corporation or character name
     */
    entityName?: string;
    /**
     * key entity ID, either corporation or character ID
     */
    entityID?: number;
    /**
     * Character name
     */
    charName?: string;
    /**
     * Character ID
     */
    charID?: number;
    /**
     * Corporation name
     */
    corpName?: string;
    /**
     * Corporation ID
     */
    corpID?: number;
    /**
     * key access mask
     */
    mask?: number;
    /**
     * if not -1, then the time (millis UTC) when this key will expire
     */
    expiry?: number;
    /**
     * if no -1, then the time (millis UTC) of the oldest model entities this key will allow access to
     */
    limit?: number;
    /**
     * if true, then the ESI token associated with the synchronized account which owns this key is stillvalid.  Otherwise, the key is not valid and may need to be re-authorized
     */
    tokenValid?: boolean;
}
