/**
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * EveKit Access Key Mask List
 */
export interface MaskList { 
    /**
     * access account status
     */
    ACCESS_ACCOUNT_STATUS?: number;
    /**
     * access account balance
     */
    ACCESS_ACCOUNT_BALANCE?: number;
    /**
     * access assets
     */
    ACCESS_ASSETS?: number;
    /**
     * access contact list
     */
    ACCESS_CONTACT_LIST?: number;
    /**
     * access blueprints
     */
    ACCESS_BLUEPRINTS?: number;
    /**
     * access bookmarks
     */
    ACCESS_BOOKMARKS?: number;
    /**
     * access contracts
     */
    ACCESS_CONTRACTS?: number;
    /**
     * access faction war statistics
     */
    ACCESS_FAC_WAR_STATS?: number;
    /**
     * access industry jobs
     */
    ACCESS_INDUSTRY_JOBS?: number;
    /**
     * access kill log
     */
    ACCESS_KILL_LOG?: number;
    /**
     * access asset locations
     */
    ACCESS_LOCATIONS?: number;
    /**
     * access market orders
     */
    ACCESS_MARKET_ORDERS?: number;
    /**
     * access mining ledger
     */
    ACCESS_MINING_LEDGER?: number;
    /**
     * access standings
     */
    ACCESS_STANDINGS?: number;
    /**
     * access wallet journal
     */
    ACCESS_WALLET_JOURNAL?: number;
    /**
     * access wallet transactions
     */
    ACCESS_WALLET_TRANSACTIONS?: number;
    /**
     * allow changes to meta-data
     */
    ALLOW_METADATA_CHANGES?: number;
    /**
     * access character calendar event attendees
     */
    ACCESS_CALENDAR_EVENT_ATTENDEES?: number;
    /**
     * access character fleet information
     */
    ACCESS_CHARACTER_FLEETS?: number;
    /**
     * access character sheet
     */
    ACCESS_CHARACTER_SHEET?: number;
    /**
     * access character chat channels
     */
    ACCESS_CHAT_CHANNELS?: number;
    /**
     * access character contact notifications
     */
    ACCESS_CONTACT_NOTIFICATIONS?: number;
    /**
     * access character ship fittings
     */
    ACCESS_FITTINGS?: number;
    /**
     * access character mail
     */
    ACCESS_MAIL?: number;
    /**
     * access character mailing lists
     */
    ACCESS_MAILING_LISTS?: number;
    /**
     * access character medals
     */
    ACCESS_MEDALS?: number;
    /**
     * access character notifications
     */
    ACCESS_NOTIFICATIONS?: number;
    /**
     * access character research
     */
    ACCESS_RESEARCH?: number;
    /**
     * access character skill in training
     */
    ACCESS_SKILL_IN_TRAINING?: number;
    /**
     * access character skill queue
     */
    ACCESS_SKILL_QUEUE?: number;
    /**
     * access character upcoming calendar events
     */
    ACCESS_UPCOMING_CALENDAR_EVENTS?: number;
    /**
     * access corporation container log
     */
    ACCESS_CONTAINER_LOG?: number;
    /**
     * access corporation sheet
     */
    ACCESS_CORPORATION_SHEET?: number;
    /**
     * access corporation medals
     */
    ACCESS_CORPORATION_MEDALS?: number;
    /**
     * access corporation memeber medals
     */
    ACCESS_MEMBER_MEDALS?: number;
    /**
     * access corporation member security
     */
    ACCESS_MEMBER_SECURITY?: number;
    /**
     * access corporation member security log
     */
    ACCESS_MEMBER_SECURITY_LOG?: number;
    /**
     * access corporation member tracking
     */
    ACCESS_MEMBER_TRACKING?: number;
    /**
     * access corporation shareholders
     */
    ACCESS_SHAREHOLDERS?: number;
    /**
     * access corporation starbase list
     */
    ACCESS_STARBASE_LIST?: number;
    /**
     * access corporation structures
     */
    ACCESS_STRUCTURES?: number;
    /**
     * access corporation titles
     */
    ACCESS_CORPORATION_TITLES?: number;
}
