/**
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlanetaryPinContent } from './planetaryPinContent';
import { PlanetaryPinHead } from './planetaryPinHead';


/**
 * Model data common properties
 */
export interface PlanetaryPin { 
    /**
     * Unique ID
     */
    cid?: number;
    /**
     * EveKit release version
     */
    eveKitVersion?: number;
    /**
     * Model lifeline start (milliseconds UTC)
     */
    lifeStart?: number;
    /**
     * Model lifeline end (milliseconds UTC), MAX_LONG for live data
     */
    lifeEnd?: number;
    planetID?: number;
    pinID?: number;
    typeID?: number;
    schematicID?: number;
    lastCycleStart?: number;
    cycleTime?: number;
    quantityPerCycle?: number;
    installTime?: number;
    expiryTime?: number;
    productTypeID?: number;
    longitude?: number;
    latitude?: number;
    headRadius?: number;
    heads?: Array<PlanetaryPinHead>;
    contents?: Array<PlanetaryPinContent>;
    /**
     * lifeStart Date
     */
    lifeStartDate?: Date;
    /**
     * lifeEnd Date
     */
    lifeEndDate?: Date;
    /**
     * lastCycleStart Date
     */
    lastCycleStartDate?: Date;
    /**
     * installTime Date
     */
    installTimeDate?: Date;
    /**
     * expiryTime Date
     */
    expiryTimeDate?: Date;
}
