/**
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Model data common properties
 */
export interface Starbase { 
    /**
     * Unique ID
     */
    cid?: number;
    /**
     * EveKit release version
     */
    eveKitVersion?: number;
    /**
     * Model lifeline start (milliseconds UTC)
     */
    lifeStart?: number;
    /**
     * Model lifeline end (milliseconds UTC), MAX_LONG for live data
     */
    lifeEnd?: number;
    starbaseID?: number;
    typeID?: number;
    systemID?: number;
    moonID?: number;
    state?: string;
    unanchorAt?: number;
    reinforcedUntil?: number;
    onlinedSince?: number;
    fuelBayView?: string;
    fuelBayTake?: string;
    anchor?: string;
    unanchor?: string;
    online?: string;
    offline?: string;
    allowCorporationMembers?: boolean;
    allowAllianceMembers?: boolean;
    useAllianceStandings?: boolean;
    attackStandingThreshold?: number;
    attackSecurityStatusThreshold?: number;
    attackIfOtherSecurityStatusDropping?: boolean;
    attackIfAtWar?: boolean;
    /**
     * lifeStart Date
     */
    lifeStartDate?: Date;
    /**
     * lifeEnd Date
     */
    lifeEndDate?: Date;
    /**
     * unanchorAt Date
     */
    unanchorAtDate?: Date;
    /**
     * reinforcedUntil Date
     */
    reinforcedUntilDate?: Date;
    /**
     * onlinedSince Date
     */
    onlinedSinceDate?: Date;
}
