/**
 * EveKit Model API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Model data common properties
 */
export interface Structure { 
    /**
     * Unique ID
     */
    cid?: number;
    /**
     * EveKit release version
     */
    eveKitVersion?: number;
    /**
     * Model lifeline start (milliseconds UTC)
     */
    lifeStart?: number;
    /**
     * Model lifeline end (milliseconds UTC), MAX_LONG for live data
     */
    lifeEnd?: number;
    structureID?: number;
    corporationID?: number;
    fuelExpires?: number;
    nextReinforceApply?: number;
    nextReinforceHour?: number;
    nextReinforceWeekday?: number;
    profileID?: number;
    reinforceHour?: number;
    reinforceWeekday?: number;
    state?: string;
    stateTimerEnd?: number;
    stateTimerStart?: number;
    systemID?: number;
    typeID?: number;
    unanchorsAt?: number;
    /**
     * lifeStart Date
     */
    lifeStartDate?: Date;
    /**
     * lifeEnd Date
     */
    lifeEndDate?: Date;
    /**
     * fuelExpires Date
     */
    fuelExpiresDate?: Date;
    /**
     * nextReinforceApply Date
     */
    nextReinforceApplyDate?: Date;
    /**
     * stateTimerEnd Date
     */
    stateTimerEndDate?: Date;
    /**
     * stateTimerStart Date
     */
    stateTimerStartDate?: Date;
    /**
     * unanchorsAt Date
     */
    unanchorsAtDate?: Date;
}
