/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180529
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ChrAncestry {
    ancestryID?: number;
    ancestryName?: string;
    bloodlineID?: number;
    description?: string;
    perception?: number;
    willpower?: number;
    charisma?: number;
    memory?: number;
    intelligence?: number;
    iconID?: number;
    shortDescription?: string;
}
