/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180713
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CrpNpcCorporation {
    corporationID?: number;
    size?: string;
    extent?: string;
    solarSystemID?: number;
    investorID1?: number;
    investorShares1?: number;
    investorID2?: number;
    investorShares2?: number;
    investorID3?: number;
    investorShares3?: number;
    investorID4?: number;
    investorShares4?: number;
    friendID?: number;
    enemyID?: number;
    publicShares?: number;
    initialPrice?: number;
    minSecurity?: number;
    scattered?: number;
    fringe?: number;
    corridor?: number;
    hub?: number;
    border?: number;
    factionID?: number;
    sizeFactor?: number;
    stationCount?: number;
    stationSystemCount?: number;
    description?: string;
    iconID?: number;
}
