/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180529
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DgmExpression {
    expressionID?: number;
    operandID?: number;
    arg1?: number;
    arg2?: number;
    expressionValue?: string;
    description?: string;
    expressionName?: string;
    expressionTypeID?: number;
    expressionGroupID?: number;
    expressionAttributeID?: number;
}
