/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180713
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InvContrabandType {
    standingLoss?: number;
    confiscateMinSec?: number;
    fineByValue?: number;
    attackMinSec?: number;
    typeID?: number;
    factionID?: number;
}
