/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180713
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MapCelestialStatistic {
    celestialID?: number;
    temperature?: number;
    spectralClass?: string;
    luminosity?: number;
    age?: number;
    life?: number;
    orbitRadius?: number;
    eccentricity?: number;
    massDust?: number;
    massGas?: number;
    fragmented?: boolean;
    density?: number;
    surfaceGravity?: number;
    escapeVelocity?: number;
    orbitPeriod?: number;
    rotationRate?: number;
    locked?: boolean;
    pressure?: number;
    radius?: number;
    mass?: number;
}
