/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180713
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RamAssemblyLineType {
    assemblyLineTypeID?: number;
    assemblyLineTypeName?: string;
    description?: string;
    baseTimeMultiplier?: number;
    baseMaterialMultiplier?: number;
    baseCostMultiplier?: number;
    volume?: number;
    activityID?: number;
    minCostPerHour?: number;
}
