/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180529
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StaOperation {
    operationID?: number;
    activityID?: number;
    operationName?: string;
    description?: string;
    fringe?: number;
    corridor?: number;
    hub?: number;
    border?: number;
    ratio?: number;
    caldariStationTypeID?: number;
    minmatarStationTypeID?: number;
    amarrStationTypeID?: number;
    gallenteStationTypeID?: number;
    joveStationTypeID?: number;
}
