/**
 * EveKit SDE API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0.20180713
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StaStation {
    stationID?: number;
    security?: number;
    dockingCostPerVolume?: number;
    maxShipVolumeDockable?: number;
    officeRentalCost?: number;
    operationID?: number;
    stationTypeID?: number;
    corporationID?: number;
    solarSystemID?: number;
    constellationID?: number;
    regionID?: number;
    stationName?: string;
    x?: number;
    y?: number;
    z?: number;
    reprocessingEfficiency?: number;
    reprocessingStationsTake?: number;
    reprocessingHangarFlag?: number;
}
